---
# Source: adminer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adminer-release
  labels:
    app.kubernetes.io/name: adminer
    helm.sh/chart: adminer-0.2.1
    app.kubernetes.io/instance: adminer-release
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: adminer
    app.kubernetes.io/instance: adminer-release
---
# Source: adminer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-release
  labels:
    app.kubernetes.io/name: adminer
    helm.sh/chart: adminer-0.2.1
    app.kubernetes.io/instance: adminer-release
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adminer
      app.kubernetes.io/instance: adminer-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adminer
        app.kubernetes.io/instance: adminer-release
    spec:
      containers:
        - name: adminer
          image: "adminer:4.8.1-standalone"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ADMINER_PLUGINS
              value:
            - name: ADMINER_DESIGN
              value: pepa-linha
            - name: ADMINER_DEFAULT_SERVER
              value:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-adminer
spec:
  rules:
  - host: adminer.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminer-release
            port:
              number: 80
  ingressClassName: nginx
