apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-adminer
  namespace: default
spec:
  rules:
  - host: adminer.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminer-release
            port:
              number: 80
  ingressClassName: nginx
